{% set name = "expecttest" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/expecttest-{{ version }}.tar.gz
  sha256: 6e8512fb86523ada1f94fd1b14e280f924e379064bb8a29ee399950e513eeccd

build:
  script: {{ PYTHON }} -m pip install . --no-deps  --no-build-isolation --ignore-installed -vv
  number: 0
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - expecttest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ezyang/expecttest
  summary: This library implements expect tests (also known as "golden" tests).
  description: This library implements expect tests (also known as "golden" tests).
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/ezyang/expecttest
  doc_url: https://github.com/ezyang/expecttest

extra:
  recipe-maintainers:
    - tobijk
