{% set name = "expecttest" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/expecttest-{{ version }}.tar.gz
  sha256: 83057695811d94128aed13ed094a070db90e0a92ea40071f8ee073cbab57149a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - expecttest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ezyang/expecttest
  summary: This library implements expect tests (also known as "golden" tests).
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/ezyang/expecttest
  doc_url: https://github.com/ezyang/expecttest

extra:
  recipe-maintainers:
    - tobijk
